# Generated by Django 5.2.3 on 2025-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('last_name', 'first_name', 'middle_name', 'birth_date')},
        ),
        migrations.RemoveField(
            model_name='deletionrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_safety_commission_member',
            field=models.BooleanField(default=False, verbose_name='Член комиссии по охране труда'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Детали'),
        ),
    ]
