# Generated by Django 5.2 on 2025-04-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
    ]
