# Generated by Django 5.2 on 2025-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_position_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_external_part_time',
            field=models.BooleanField(default=False, verbose_name='Внешний совместитель'),
        ),
    ]
