# Generated by Django 5.2 on 2025-04-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_position_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('recurrence_period', models.PositiveIntegerField(blank=True, help_text='Укажите, через сколько лет требуется повторное обучение (оставьте пустым, если не требуется).', null=True, verbose_name='Периодичность повторного обучения (годы)')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
            },
        ),
    ]
