# Generated by Django 5.2.3 on 2025-06-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_deletionrequest_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Фамилия'),
        ),
    ]
