# Generated by Django 5.2 on 2025-04-16 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_trainingprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField(verbose_name='Дата прохождения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Сотрудник')),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.trainingprogram', verbose_name='Программа обучения')),
            ],
            options={
                'verbose_name': 'Запись об обучении',
                'verbose_name_plural': 'Записи об обучении',
                'unique_together': {('employee', 'training_program', 'completion_date')},
            },
        ),
    ]
