# Generated by Django 5.2.3 on 2025-06-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='training_documents/', verbose_name='Скан документа'),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
    ]
