# Generated by Django 5.2 on 2025-05-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='details',
            field=models.TextField(blank=True, verbose_name='Детали'),
        ),
    ]
