# Generated by Django 5.2.3 on 2025-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='position',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='position',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='position',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Педагогический работник'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
