# Generated by Django 5.2.3 on 2025-06-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_remove_position_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='is_manager',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_teacher',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Педагогический работник'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
