from datetime import date

employees_data_list = [
    {
        "last_name": "Акимов",
        "first_name": "Дмитрий",
        "middle_name": "Николаевич",
        "birth_date": date(1974, 2, 15),
        "position": "Заместитель руководителя отдела",
        "department": "ОДО",
    },
    {
        "last_name": "Алейникова",
        "first_name": "Ирина",
        "middle_name": "Владимировна",
        "birth_date": date(1987, 1, 1),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Александрова",
        "first_name": "Ольга",
        "middle_name": "Викторовна",
        "birth_date": date(1982, 6, 6),
        "position": "Старший инспектор",
        "department": "ОСПР",
    },
    {
        "last_name": "Алексеева",
        "first_name": "Наталья",
        "middle_name": "Валентиновна",
        "birth_date": date(1986, 9, 26),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Андрианов",
        "first_name": "Дмитрий",
        "middle_name": "Александрович",
        "birth_date": date(1982, 7, 27),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Бабикова",
        "first_name": "Марина",
        "middle_name": "Ивановна",
        "birth_date": date(1958, 8, 21),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Бабурина",
        "first_name": "Ирина",
        "middle_name": "Михайловна",
        "birth_date": date(1960, 8, 9),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Бакал",
        "first_name": "Ирина",
        "middle_name": "Анатольевна",
        "birth_date": date(1970, 6, 18),
        "position": "Заместитель руководителя отдела",
        "department": "УМО",
    },
    {
        "last_name": "Барканова",
        "first_name": "Ирина",
        "middle_name": "Владимировна",
        "birth_date": date(1995, 3, 30),
        "position": "Методист",
        "department": "УМО",
    },
    {
        "last_name": "Береговая",
        "first_name": "Ольга",
        "middle_name": "Валентиновна",
        "birth_date": date(1971, 12, 10),
        "position": "Старший инспектор",
        "department": "ФЭО",
    },
    {
        "last_name": "Благовисная",
        "first_name": "Юлия",
        "middle_name": "Михайловна",
        "birth_date": date(1979, 4, 2),
        "position": "Руководитель отдела",
        "department": "ОК",
    },
    {
        "last_name": "Болдырева",
        "first_name": "Светлана",
        "middle_name": "Владимировна",
        "birth_date": date(1976, 5, 7),
        "position": "Медицинская сестра",
        "department": "МО",
    },
    {
        "last_name": "Бутылин",
        "first_name": "Владимир",
        "middle_name": "Леонидович",
        "birth_date": date(1950, 1, 23),
        "position": "Водитель автомобиля",
        "department": "ОМТО",
    },
    {
        "last_name": "Варакина",
        "first_name": "Наталья",
        "middle_name": "Николаевна",
        "birth_date": date(1981, 1, 5),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Варнавина",
        "first_name": "Светлана",
        "middle_name": "Константиновна",
        "birth_date": date(1956, 10, 25),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Васильева",
        "first_name": "Наталья",
        "middle_name": "Владимировна",
        "birth_date": date(1976, 8, 6),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Велицкая",
        "first_name": "Эллида",
        "middle_name": "Витальеевна",
        "birth_date": date(1980, 6, 20),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Велицкий",
        "first_name": "Владимир",
        "middle_name": "Александрович",
        "birth_date": date(1982, 5, 5),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Вецко",
        "first_name": "Наталья",
        "middle_name": "Александровна",
        "birth_date": date(1973, 7, 26),
        "position": "Заместитель директора (по учебно-методической работе)",
        "department": "Руководство",
    },
    {
        "last_name": "Вихарева",
        "first_name": "Ольга",
        "middle_name": "Германовна",
        "birth_date": date(1973, 1, 20),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Волкова",
        "first_name": "Варвара",
        "middle_name": "Александровна",
        "birth_date": date(1995, 10, 23),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Волкова",
        "first_name": "Дарья",
        "middle_name": "Сергеевна",
        "birth_date": date(1998, 2, 14),
        "position": "Педагог-организатор",
        "department": "ООПиВР",
    },
    {
        "last_name": "Воронина",
        "first_name": "Анна",
        "middle_name": "Юрьевна",
        "birth_date": date(1985, 6, 3),
        "position": "Старший воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Гаева",
        "first_name": "Евгения",
        "middle_name": "Юрьевна",
        "birth_date": date(1970, 8, 29),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Герасимова",
        "first_name": "Ольга",
        "middle_name": "Николаевна",
        "birth_date": date(1990, 9, 8),
        "position": "Инспектор",
        "department": "ОПО",
    },
    {
        "last_name": "Гиревая",
        "first_name": "Ханифа",
        "middle_name": "Яншаевна",
        "birth_date": date(1970, 4, 6),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Гольтяева",
        "first_name": "Наталья",
        "middle_name": "Сергеевна",
        "birth_date": date(1978, 7, 25),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Горошенский",
        "first_name": "Василий",
        "middle_name": "Павлович",
        "birth_date": date(1986, 9, 30),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Григорьева",
        "first_name": "Юлия",
        "middle_name": "Анатольевна",
        "birth_date": date(1998, 2, 15),
        "position": "Социальный педагог",
        "department": "ОСПР",
    },
    {
        "last_name": "Груздева",
        "first_name": "Марина",
        "middle_name": "Борисовна",
        "birth_date": date(1964, 10, 19),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Гузенко",
        "first_name": "Борис",
        "middle_name": "Яковлевич",
        "birth_date": date(1959, 5, 14),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Даниелян",
        "first_name": "Татьяна",
        "middle_name": "Эдуардовна",
        "birth_date": date(1997, 11, 18),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Денисенко",
        "first_name": "Лариса",
        "middle_name": "Анатольевна",
        "birth_date": date(1970, 6, 26),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Дмитриенко",
        "first_name": "Екатерина",
        "middle_name": "Владимировна",
        "birth_date": date(1981, 2, 18),
        "position": "Заместитель руководителя отдела",
        "department": "ОК",
    },
    {
        "last_name": "Дубова",
        "first_name": "Марина",
        "middle_name": "Сергеевна",
        "birth_date": date(1988, 3, 23),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Дядюн",
        "first_name": "Ирина",
        "middle_name": "Григорьевна",
        "birth_date": date(1964, 12, 14),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Епифанова",
        "first_name": "Анна",
        "middle_name": "Евгеньевна",
        "birth_date": date(1979, 8, 1),
        "position": "Педагог-организатор",
        "department": "ООПиВР",
    },
    {
        "last_name": "Еремеева",
        "first_name": "Анастасия",
        "middle_name": "Игоревна",
        "birth_date": date(2000, 6, 11),
        "position": "Педагог-психолог",
        "department": "ОСПР",
    },
    {
        "last_name": "Жукова",
        "first_name": "Ольга",
        "middle_name": "Юрьевна",
        "birth_date": date(1977, 12, 22),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Залесова",
        "first_name": "Ксения",
        "middle_name": "Сергеевна",
        "birth_date": date(2001, 4, 29),
        "position": "Социальный педагог",
        "department": "ОСПР",
    },
    {
        "last_name": "Запруднов",
        "first_name": "Филипп",
        "middle_name": "Александрович",
        "birth_date": date(1971, 3, 25),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Зверев",
        "first_name": "Вячеслав",
        "middle_name": "Владимирович",
        "birth_date": date(1970, 12, 7),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Звягинцев",
        "first_name": "Андрей",
        "middle_name": "Адреевич",
        "birth_date": date(1995, 9, 5),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Земелева",
        "first_name": "Виктория",
        "middle_name": "Викторовна",
        "birth_date": date(1981, 2, 19),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Золотарев",
        "first_name": "Роман",
        "middle_name": "Васильевич",
        "birth_date": date(1992, 10, 20),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Зубань",
        "first_name": "Мария",
        "middle_name": "Алексеевна",
        "birth_date": date(1990, 12, 12),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Иванова",
        "first_name": "Екатерина",
        "middle_name": "Андреевна",
        "birth_date": date(1978, 7, 2),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Иванова",
        "first_name": "Людмила",
        "middle_name": "Ивановна",
        "birth_date": date(1980, 2, 22),
        "position": "Инспектор",
        "department": "ОМТО",
    },
    {
        "last_name": "Кабанцов",
        "first_name": "Сергей",
        "middle_name": "Викторович",
        "birth_date": date(1975, 11, 3),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Казанков",
        "first_name": "Александр",
        "middle_name": "Владимирович",
        "birth_date": date(1984, 4, 29),
        "position": "Инспектор",
        "department": "ОМТО",
    },
    {
        "last_name": "Калтышева",
        "first_name": "Наталья",
        "middle_name": "Владимировна",
        "birth_date": date(1963, 3, 31),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Карабельникова",
        "first_name": "Ирина",
        "middle_name": "Викторовна",
        "birth_date": date(1992, 9, 14),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Кареглазова",
        "first_name": "Анна",
        "middle_name": "Алексеевна",
        "birth_date": date(1995, 8, 29),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Карпов",
        "first_name": "Павел",
        "middle_name": "Евгеньевич",
        "birth_date": date(1982, 7, 2),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Каширская",
        "first_name": "Регина",
        "middle_name": "Сергеевна",
        "birth_date": date(1997, 4, 7),
        "position": "Педагог-организатор",
        "department": "ООПиВР",
    },
    {
        "last_name": "Каюкова",
        "first_name": "Елизавета",
        "middle_name": "Александровна",
        "birth_date": date(2001, 12, 13),
        "position": "Педагог-организатор",
        "department": "ООПиВР",
    },
    {
        "last_name": "Клементьева (Кутузова)",
        "first_name": "Надежда",
        "middle_name": "Александровна",
        "birth_date": date(1988, 10, 2),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Климова",
        "first_name": "Ирина",
        "middle_name": "Анатольевна",
        "birth_date": date(1970, 5, 3),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Коваленко",
        "first_name": "Дмитрий",
        "middle_name": "Андреевич",
        "birth_date": date(1989, 8, 1),
        "position": "Руководитель отдела",
        "department": "УМО",
    },
    {
        "last_name": "Коваленко",
        "first_name": "Наталья",
        "middle_name": "Викторовна",
        "birth_date": date(1986, 4, 13),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Колечкова",
        "first_name": "Надежда",
        "middle_name": "Борисовна",
        "birth_date": None,
        "position": "Медицинская сестра",
        "department": "МО",
    },
    {
        "last_name": "Колышева",
        "first_name": "Наталья",
        "middle_name": "Сергеевна",
        "birth_date": date(1979, 1, 10),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Комиссаров",
        "first_name": "Алексей",
        "middle_name": "Александрович",
        "birth_date": date(1988, 11, 28),
        "position": "Заместитель руководителя отдела",
        "department": "ОМТО",
    },
    {
        "last_name": "Кончева",
        "first_name": "Нина",
        "middle_name": "Павловна",
        "birth_date": date(1948, 7, 3),
        "position": "Врач-педиатр",
        "department": "МО",
    },
    {
        "last_name": "Коренькова",
        "first_name": "Наталья",
        "middle_name": "Германовна",
        "birth_date": date(1976, 9, 4),
        "position": "Педагог дополнительного образования (заведующий библиотекой)",
        "department": "ОДО",
    },
    {
        "last_name": "Коробкин",
        "first_name": "Александр",
        "middle_name": "Михайлович",
        "birth_date": date(1981, 5, 30),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Королева",
        "first_name": "Екатерина",
        "middle_name": "Валентиновна",
        "birth_date": date(1980, 8, 7),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Короткова",
        "first_name": "Галина",
        "middle_name": "Евгеньевна",
        "birth_date": date(1982, 11, 1),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Корчагова",
        "first_name": "Елена",
        "middle_name": "Геннадьевна",
        "birth_date": date(1975, 3, 28),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Кочнёва",
        "first_name": "Екатерина",
        "middle_name": "Владимировна",
        "birth_date": date(1991, 6, 12),
        "position": "Инспектор (по инновационным технологиям)",
        "department": "УМО",
    },
    {
        "last_name": "Кравцова",
        "first_name": "Наталия",
        "middle_name": "Аловсатовна",
        "birth_date": date(1984, 1, 10),
        "position": "Педагог-организатор",
        "department": "ООПиВР",
    },
    {
        "last_name": "Крамаренко",
        "first_name": "Руслан",
        "middle_name": "Викторович",
        "birth_date": date(1982, 7, 6),
        "position": "Старший инспектор",
        "department": "ООПиВР",
    },
    {
        "last_name": "Кривцанов",
        "first_name": "Алексей",
        "middle_name": "Владимирович",
        "birth_date": date(1988, 3, 26),
        "position": "Руководитель отдела",
        "department": "ООБ",
    },
    {
        "last_name": "Кузвесова",
        "first_name": "Юлия",
        "middle_name": "Романовна",
        "birth_date": date(1997, 6, 4),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Курдюкова",
        "first_name": "Полина",
        "middle_name": "Юрьевна",
        "birth_date": date(1994, 7, 10),
        "position": "Методист",
        "department": "ОДО",
    },
    {
        "last_name": "Кутузова",
        "first_name": "Наталья",
        "middle_name": "Васильевна",
        "birth_date": date(1979, 12, 15),
        "position": "Начальник отдела (врач-педиатр)",
        "department": "МО",
    },
    {
        "last_name": "Кутузова (Козлова)",
        "first_name": "Наталья",
        "middle_name": "Викторовна",
        "birth_date": date(1975, 6, 14),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Лагуткина",
        "first_name": "Анастасия",
        "middle_name": "Владимировна",
        "birth_date": date(1993, 4, 21),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Ларионов",
        "first_name": "Константин",
        "middle_name": "Владимирович",
        "birth_date": date(1979, 11, 23),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Лисицина",
        "first_name": "Анна",
        "middle_name": "Владимировна",
        "birth_date": date(1989, 8, 7),
        "position": "Педагог-организатор",
        "department": "ООПиВР",
    },
    {
        "last_name": "Литвиненко",
        "first_name": "Алексей",
        "middle_name": "Викторович",
        "birth_date": date(1966, 6, 10),
        "position": "Старший инспектор",
        "department": "ОК",
    },
    {
        "last_name": "Лучутенкова",
        "first_name": "Людмила",
        "middle_name": "Сергеевна",
        "birth_date": date(1954, 8, 29),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Максимов",
        "first_name": "Евгений",
        "middle_name": "Александрович",
        "birth_date": date(1987, 10, 23),
        "position": "Руководитель отдела",
        "department": "ОМТО",
    },
    {
        "last_name": "Маркелова",
        "first_name": "Ксения",
        "middle_name": "Сергеевна",
        "birth_date": date(1997, 11, 22),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Мартынова",
        "first_name": "Светлана",
        "middle_name": "Юрьевна",
        "birth_date": date(1967, 10, 21),
        "position": "Руководитель отдела",
        "department": "ОСПР",
    },
    {
        "last_name": "Марченко",
        "first_name": "Людмила",
        "middle_name": "Анатольевна",
        "birth_date": date(1989, 1, 16),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Матвеев",
        "first_name": "Антон",
        "middle_name": "Владимирович",
        "birth_date": date(1990, 7, 21),
        "position": "Старший инспектор",
        "department": "ОПО",
    },
    {
        "last_name": "Мелик",
        "first_name": "Александр",
        "middle_name": "Сергеевич",
        "birth_date": date(1985, 3, 7),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Мельцева",
        "first_name": "Александра",
        "middle_name": "Олеговна",
        "birth_date": date(1998, 3, 26),
        "position": "Инспектор",
        "department": "ОДОб",
    },
    {
        "last_name": "Меркулова",
        "first_name": "Надежда",
        "middle_name": "Евгеньевна",
        "birth_date": date(1991, 3, 31),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Нагорянская",
        "first_name": "Наталья",
        "middle_name": "Александровна",
        "birth_date": date(1974, 12, 30),
        "position": "Инспектор",
        "department": "ФЭО",
    },
    {
        "last_name": "Надеин",
        "first_name": "Константин",
        "middle_name": "Александрович",
        "birth_date": date(1975, 6, 16),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Назаренко",
        "first_name": "Евгения",
        "middle_name": "Владимировна",
        "birth_date": date(1982, 3, 9),
        "position": "Заместитель директора (по организационным вопросам и контролю)",
        "department": "Руководство",
    },
    {
        "last_name": "Недопекина",
        "first_name": "Елизавета",
        "middle_name": "Игоревна",
        "birth_date": date(1998, 2, 13),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Незговоров",
        "first_name": "Александр",
        "middle_name": "Владимирович",
        "birth_date": date(1992, 1, 13),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Незговорова (Сорокина)",
        "first_name": "Анна",
        "middle_name": "Аркадьевна",
        "birth_date": date(1996, 4, 30),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Никитина",
        "first_name": "Евгения",
        "middle_name": "Васильевна",
        "birth_date": date(1990, 1, 26),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Николаева",
        "first_name": "Ирина",
        "middle_name": "Васильевна",
        "birth_date": None,
        "position": "Медицинская сестра",
        "department": "МО",
    },
    {
        "last_name": "Охремчук (Пяшина)",
        "first_name": "Александра",
        "middle_name": "Сергеевна",
        "birth_date": date(1994, 8, 2),
        "position": "Старший инспектор",
        "department": "ОК",
    },
    {
        "last_name": "Павлова",
        "first_name": "Вера",
        "middle_name": "Михайловна",
        "birth_date": date(1960, 2, 15),
        "position": "Старший методист",
        "department": "УМО",
    },
    {
        "last_name": "Папевская (Филиппова)",
        "first_name": "Жанны",
        "middle_name": "Борисовны",
        "birth_date": date(1993, 9, 27),
        "position": "Старший инспектор",
        "department": "ОДОб",
    },
    {
        "last_name": "Паршикова",
        "first_name": "Анастасия",
        "middle_name": "Сергеевна",
        "birth_date": date(1986, 2, 10),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Петрова",
        "first_name": "Светлана",
        "middle_name": "Вячеславна",
        "birth_date": date(1976, 6, 19),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Пискунов",
        "first_name": "Владимир",
        "middle_name": "Валерьевич",
        "birth_date": date(1978, 10, 12),
        "position": "Старший инспектор",
        "department": "ООБ",
    },
    {
        "last_name": "Плечко",
        "first_name": "Татьяна",
        "middle_name": "Александровна",
        "birth_date": date(1980, 1, 27),
        "position": "Инспектор",
        "department": "ФЭО",
    },
    {
        "last_name": "Плотникова",
        "first_name": "Юлия",
        "middle_name": "Николаевна",
        "birth_date": date(1973, 3, 20),
        "position": "Медицинская сестра",
        "department": "МО",
    },
    {
        "last_name": "Полотебнов",
        "first_name": "Александр",
        "middle_name": "Сергеевич",
        "birth_date": date(1986, 9, 25),
        "position": "Методист",
        "department": "УМО",
    },
    {
        "last_name": "Полякова",
        "first_name": "Анна",
        "middle_name": "Сергеевна",
        "birth_date": date(1991, 8, 14),
        "position": "Старший воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Пономарева",
        "first_name": "Юлия",
        "middle_name": "Николаевна",
        "birth_date": date(1988, 6, 16),
        "position": "Инспектор",
        "department": "ОК",
    },
    {
        "last_name": "Прищепа",
        "first_name": "Лариса",
        "middle_name": "Николаевна",
        "birth_date": date(1956, 12, 28),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Пяшин",
        "first_name": "Сергей",
        "middle_name": "Александрович",
        "birth_date": date(1970, 4, 25),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Ревуненков",
        "first_name": "Денис",
        "middle_name": "Игоревич",
        "birth_date": date(1988, 12, 9),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Руденко",
        "first_name": "Екатерина",
        "middle_name": "Олеговна",
        "birth_date": date(1979, 8, 17),
        "position": "Руководитель отдела",
        "department": "ОДОб",
    },
    {
        "last_name": "Рыбак",
        "first_name": "Андрей",
        "middle_name": "Петрович",
        "birth_date": date(1983, 3, 17),
        "position": "Старший воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Рябцев",
        "first_name": "Сергей",
        "middle_name": "Анатольевич",
        "birth_date": None,
        "position": "Водитель автомобиля",
        "department": "ОМТО",
    },
    {
        "last_name": "Сабелькина",
        "first_name": "Елена",
        "middle_name": "Владимировна",
        "birth_date": date(1982, 1, 9),
        "position": "Инспектор",
        "department": "ОМТО",
    },
    {
        "last_name": "Саенко (Лепко)",
        "first_name": "Надежда",
        "middle_name": "Сергеевна",
        "birth_date": date(1987, 10, 20),
        "position": "Руководитель отдела (главный бухгалтер)",
        "department": "ФЭО",
    },
    {
        "last_name": "Семёнов",
        "first_name": "Сергей",
        "middle_name": "Сергеевич",
        "birth_date": date(1987, 11, 13),
        "position": "Инспектор",
        "department": "ОМТО",
    },
    {
        "last_name": "Скворцов",
        "first_name": "Андрей",
        "middle_name": "Юрьевич",
        "birth_date": date(1984, 1, 12),
        "position": "Старший воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Скрипченкова",
        "first_name": "Светлана",
        "middle_name": "Владимировна",
        "birth_date": None,
        "position": "Врач-педиатр",
        "department": "МО",
    },
    {
        "last_name": "Смирнова",
        "first_name": "Ирина",
        "middle_name": "Николаевна",
        "birth_date": date(1969, 11, 20),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Смирнова",
        "first_name": "Татьяна",
        "middle_name": "Александровна",
        "birth_date": date(1986, 1, 11),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Солодовников",
        "first_name": "Владимир",
        "middle_name": "Александрович",
        "birth_date": date(1976, 12, 21),
        "position": "Инспектор",
        "department": "ОК",
    },
    {
        "last_name": "Сомова",
        "first_name": "Валерия",
        "middle_name": "Юрьевна",
        "birth_date": date(1999, 6, 26),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Спирина",
        "first_name": "Ирина",
        "middle_name": "Владимировна",
        "birth_date": date(1964, 9, 21),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Спирина",
        "first_name": "Мария",
        "middle_name": "Олеговна",
        "birth_date": date(1995, 8, 4),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Стеценко",
        "first_name": "Олеся",
        "middle_name": "Николаевна",
        "birth_date": date(1982, 7, 8),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Субботин",
        "first_name": "Николай",
        "middle_name": "Сергеевич",
        "birth_date": date(1980, 12, 27),
        "position": "Старший инспектор",
        "department": "ОМТО",
    },
    {
        "last_name": "Тагирова (Езварина)",
        "first_name": "Елена",
        "middle_name": "Львовна",
        "birth_date": date(1965, 12, 17),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Тимошкова",
        "first_name": "Алина",
        "middle_name": "Сергеевна",
        "birth_date": date(1992, 3, 11),
        "position": "Социальный педагог",
        "department": "ОСПР",
    },
    {
        "last_name": "Тихонова",
        "first_name": "Полина",
        "middle_name": "Алексеевна",
        "birth_date": date(1997, 5, 30),
        "position": "Старший инспектор",
        "department": "ОДОб",
    },
    {
        "last_name": "Ткаченко",
        "first_name": "Алина",
        "middle_name": "Андреевна",
        "birth_date": date(1989, 11, 15),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Толстенко",
        "first_name": "Ирина",
        "middle_name": "Анатольевна",
        "birth_date": date(1991, 11, 16),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Толстик",
        "first_name": "Елена",
        "middle_name": "Юрьевна",
        "birth_date": date(1972, 9, 28),
        "position": "Педагог-психолог",
        "department": "ОСПР",
    },
    {
        "last_name": "Угланова",
        "first_name": "Мария",
        "middle_name": "Валерьевна",
        "birth_date": date(1992, 3, 24),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Уледева",
        "first_name": "Ольга",
        "middle_name": "Сергеевна",
        "birth_date": date(1986, 8, 21),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Ульянова",
        "first_name": "Ангелина",
        "middle_name": "Олеговна",
        "birth_date": date(1992, 4, 24),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Урбаньски",
        "first_name": "Светлана",
        "middle_name": "Витальевна",
        "birth_date": date(1998, 11, 5),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Фадеева",
        "first_name": "Вера",
        "middle_name": "Кузьминична",
        "birth_date": date(1954, 7, 6),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Федорова",
        "first_name": "Надежда",
        "middle_name": "Александровна",
        "birth_date": date(1973, 9, 24),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Фетисова",
        "first_name": "Анна",
        "middle_name": "Юрьевна",
        "birth_date": date(1974, 12, 18),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Фишева",
        "first_name": "Ольга",
        "middle_name": "Михайловна",
        "birth_date": date(1963, 3, 23),
        "position": "Педагог дополнительного образования (заведующий музеем)",
        "department": "ОДО",
    },
    {
        "last_name": "Фомина",
        "first_name": "Анастасия",
        "middle_name": "Владимировна",
        "birth_date": date(1994, 9, 9),
        "position": "Педагог дополнительного образования",
        "department": "ОДО",
    },
    {
        "last_name": "Фоминская",
        "first_name": "Наталья",
        "middle_name": "Владимировна",
        "birth_date": date(1969, 6, 6),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Харитонова",
        "first_name": "Виктория",
        "middle_name": "Евгеньевна",
        "birth_date": date(1987, 4, 2),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Хаттунен",
        "first_name": "Маргарита",
        "middle_name": "Владимировна",
        "birth_date": date(1986, 5, 27),
        "position": "Старший воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Хачатуров",
        "first_name": "Григорий",
        "middle_name": "Эдуардовича",
        "birth_date": date(1990, 9, 25),
        "position": "Руководитель отделения",
        "department": "ОПО",
    },
    {
        "last_name": "Цыгикало",
        "first_name": "Наталья",
        "middle_name": "Васильевна",
        "birth_date": date(1968, 12, 5),
        "position": "Учитель",
        "department": "УМО",
    },
    {
        "last_name": "Чернышов",
        "first_name": "Александр",
        "middle_name": "Викторович",
        "birth_date": date(1980, 2, 18),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Чипига",
        "first_name": "Юрий",
        "middle_name": "Григорьевич",
        "birth_date": date(1966, 2, 24),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Шелонина",
        "first_name": "Лилия",
        "middle_name": "Николаевна",
        "birth_date": date(1983, 11, 5),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Шендеровская",
        "first_name": "Наталья",
        "middle_name": "Васильевна",
        "birth_date": date(1967, 9, 9),
        "position": "Учитель",
        "department": "",
    },
    {
        "last_name": "Шестакова",
        "first_name": "Виктория",
        "middle_name": "Витальевна",
        "birth_date": date(1990, 10, 28),
        "position": "Педагог-организатор",
        "department": "ООПиВР",
    },
    {
        "last_name": "Шешина",
        "first_name": "Светлана",
        "middle_name": "Георгиевна",
        "birth_date": date(1963, 11, 17),
        "position": "Педагог дополнительного образования (заведующий библиотекой)",
        "department": "ОДО",
    },
    {
        "last_name": "Щербина",
        "first_name": "Игорь",
        "middle_name": "Васильевич",
        "birth_date": date(1968, 8, 15),
        "position": "Воспитатель",
        "department": "ООПиВР",
    },
    {
        "last_name": "Якунин",
        "first_name": "Никита",
        "middle_name": "Николаевич",
        "birth_date": date(1993, 1, 16),
        "position": "Инспектор",
        "department": "ООБ",
    },
    {
        "last_name": "Яценко",
        "first_name": "Сергей",
        "middle_name": "Станиславович",
        "birth_date": date(1988, 4, 30),
        "position": "Заместитель директора - руководитель отдела общественно-политической и воспитательной работы",
        "department": "Руководство",
    },
    {
        "last_name": "Яценко (Кульпина)",
        "first_name": "Валерия",
        "middle_name": "Александровна",
        "birth_date": date(1992, 12, 16),
        "position": "Врач-педиатр",
        "department": "МО",
    },
]
