# Generated by Django 5.2.3 on 2025-06-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
